#!/bin/bash

jupyter nbextension install --py vitessce
jupyter nbextension enable --py vitessce
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install vitessce-jupyter