
include: "../common.smk"
configfile: "config.yml"

BASE_URL = "https://s3.embl.de/spatialdata/spatialdata-sandbox/{dataset}.zip"


rule all:
    input:
        [ (PROCESSED_DIR / f) for f in config['output'] ]


# Unzip the downloaded zip files
rule unzip_file:
    input:
        (RAW_DIR / "{dataset}.zip")
    output:
        directory(PROCESSED_DIR / "{dataset}.zarr")
    shell:
        """
        mkdir -p data/{wildcards.dataset} &&\
        unzip {input} -d data/{wildcards.dataset} &&\
        mv data/{wildcards.dataset}/data.zarr data/processed/{wildcards.dataset}.zarr
        """

# Download visium .zip file containing single-cell data.
rule download_data:
    output:
        (RAW_DIR / "{dataset}.zip")
    params:
        file_url=BASE_URL
    shell:
        '''
        curl -L -o {output} {params.file_url}
        '''