from enum import Enum

class CoordinationType(Enum):
    DATASET = "dataset"
    EMBEDDING_TYPE = "embeddingType"
    EMBEDDING_ZOOM = "embeddingZoom"
    EMBEDDING_ROTATION = "embeddingRotation"
    EMBEDDING_TARGET_X = "embeddingTargetX"
    EMBEDDING_TARGET_Y = "embeddingTargetY"
    EMBEDDING_TARGET_Z = "embeddingTargetZ"
    SPATIAL_ZOOM = "spatialZoom"
    SPATIAL_ROTATION = "spatialRotation"
    SPATIAL_TARGET_X = "spatialTargetX"
    SPATIAL_TARGET_Y = "spatialTargetY"
    SPATIAL_TARGET_Z = "spatialTargetZ"
    HEATMAP_ZOOM_X = "heatmapZoomX"
    HEATMAP_ZOOM_Y = "heatmapZoomY"
    HEATMAP_TARGET_X = "heatmapTargetX"
    HEATMAP_TARGET_Y = "heatmapTargetY"
    CELL_FILTER = "cellFilter"
    CELL_SELECTION = "cellSelection"
    CELL_HIGHLIGHT = "cellHighlight"
    GENE_FILTER = "geneFilter"
    GENE_SELECTION = "geneSelection"
    GENE_HIGHLIGHT = "geneHighlight"
    GENE_EXPRESSION_COLORMAP = "geneExpressionColormap"
    GENE_EXPRESSION_COLORMAP_RANGE = "geneExpressionColormapRange"
    CELL_COLOR_ENCODING = "cellColorEncoding"
    SPATIAL_LAYERS = "spatialLayers"
    GENOMIC_ZOOM = "genomicZoom"
    GENOMIC_TARGET_X = "genomicTargetX"
    GENOMIC_TARGET_Y = "genomicTargetY"

class Component(Enum):
    SCATTERPLOT = "scatterplot"
    SPATIAL = "spatial"
    DESCRIPTION = "description"
    STATUS = "status"
    CELL_SETS = "cellSets"
    HEATMAP = "heatmap"
    LAYER_CONTROLLER = "layerController"
    HIGLASS = "higlass"
    CELL_SET_SIZES = "cellSetSizes"

class DataType(Enum):
    CELLS = "cells"
    CELL_SETS = "cell-sets"
    EXPRESSION_MATRIX = "expression-matrix"
    MOLECULES = "molecules"
    NEIGHBORHOODS = "neighborhoods"
    RASTER = "raster"

class FileType(Enum):
    EXPRESSION_MATRIX_ZARR = "expression-matrix.zarr"
    CLUSTERS_JSON = "clusters.json"
    GENES_JSON = "genes.json"
    CELLS_JSON = "cells.json"
    MOLECULES_JSON = "molecules.json"
    NEIGHBORHOODS_JSON = "neighborhoods.json"
    RASTER_JSON = "raster.json"
    CELL_SETS_JSON = "cell-sets.json"
