from enum import Enum

class CoordinationTypes(Enum):
    DATASET = "dataset"
    EMBEDDING_TYPE = "embeddingType"
    EMBEDDING_ZOOM = "embeddingZoom"
    EMBEDDING_ROTATION = "embeddingRotation"
    EMBEDDING_TARGET_X = "embeddingTargetX"
    EMBEDDING_TARGET_Y = "embeddingTargetY"
    EMBEDDING_TARGET_Z = "embeddingTargetZ"
    SPATIAL_ZOOM = "spatialZoom"
    SPATIAL_ROTATION = "spatialRotation"
    SPATIAL_TARGET_X = "spatialTargetX"
    SPATIAL_TARGET_Y = "spatialTargetY"
    SPATIAL_TARGET_Z = "spatialTargetZ"
    HEATMAP_ZOOM_X = "heatmapZoomX"
    HEATMAP_ZOOM_Y = "heatmapZoomY"
    HEATMAP_TARGET_X = "heatmapTargetX"
    HEATMAP_TARGET_Y = "heatmapTargetY"
    CELL_FILTER = "cellFilter"
    CELL_SELECTION = "cellSelection"
    CELL_HIGHLIGHT = "cellHighlight"
    GENE_FILTER = "geneFilter"
    GENE_SELECTION = "geneSelection"
    GENE_HIGHLIGHT = "geneHighlight"
    GENE_EXPRESSION_COLORMAP = "geneExpressionColormap"
    GENE_EXPRESSION_COLORMAP_RANGE = "geneExpressionColormapRange"
    CELL_COLOR_ENCODING = "cellColorEncoding"
    SPATIAL_LAYERS = "spatialLayers"
    GENOMIC_ZOOM = "genomicZoom"
    GENOMIC_TARGET_X = "genomicTargetX"
    GENOMIC_TARGET_Y = "genomicTargetY"