include: "../common.smk"
configfile: "config.yml"

# Rules
rule all:
    input:
        config['output']
        #(PROCESSED_DIR / "human_lymph_node_10x_visium.ome.zarr"),

# Convert the raw AnnData .h5ad file to a processed AnnData .zarr store.
rule create_zarr:
    output:
        directory(PROCESSED_DIR / "human_lymph_node_10x_visium.h5ad.zarr")
    params:
        script=(SRC_DIR / "create_zarr.py")
    shell:
        '''
        python {params.script} \
            -o {output}
        '''

