from pathlib import Path, PosixPath
from snakemake.remote.S3 import RemoteProvider as S3RemoteProvider

S3 = S3RemoteProvider()

BUCKET_NAME = "vitessce-data"
BUCKET = PosixPath(BUCKET_NAME) / "0.0.31" / "master_release"

DATA_DIR = Path("data")
PROCESSED_DIR = DATA_DIR / "processed"

subworkflow habib2017:
    workdir:
        "habib_2017_nature_methods"
    snakefile:
        "habib_2017_nature_methods/Snakefile"

rule all:
    input:
        habib2017(str(PROCESSED_DIR / "habib-2017.h5ad.zarr")),
    params:
        # This should be in output: https://github.com/snakemake/snakemake/issues/870
        habib2017=S3.remote(str(BUCKET / "habib-2017" / "habib-2017.h5ad.zarr")),
    shell:
        """
        aws s3 cp --recursive {input} s3://{params.habib2017}
        """
