name: Docs build

on: [push, pull_request]

jobs:
  docs_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - run: uv sync --extra docs  --extra notebook --extra all
      - run: uv run marimo export html-wasm docs/notebooks/marimo-wasm.mo.py -o docs/_static/mo/marimo-wasm.mo.html --mode edit
      - run: uv run make html
