name: Test Widget

on: [push, pull_request]

jobs:
  test_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.10', '3.12']
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
        env:
          UV_PYTHON: ${{ matrix.version }}
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - cwd: tests-widget
          package_json_file: tests-widget/package.json
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        working-directory: ./tests-widget
      - name: Install vitessce
        run: uv sync --extra dev --extra all --extra notebook
      - name: Export Jupyter notebook to HTML
        run: uv run jupyter nbconvert --to=html --execute docs/notebooks/__ipynb__/widget_from_dict.ipynb
      - name: Export Marimo notebook to HTML
        run: uv run marimo export html docs/notebooks/marimo.mo.py -o docs/notebooks/marimo.mo.html
      - name: Export Marimo notebook to HTML-WASM
        run: uv run marimo export html-wasm docs/notebooks/marimo-wasm.mo.py -o docs/notebooks/marimo-wasm.mo.html --mode edit
      - name: Check that widget renders in HTML output using Playwright
        run: pnpm exec playwright test
        working-directory: ./tests-widget