name: Demo data dry-run

on: [push, pull_request]

jobs:
  test_demos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Install vitessce
        run: uv sync --extra dev --extra all --extra demos
      - name: Run tests
        working-directory: ./demos
        run: uv run snakemake -j 1 --dry-run
